### PR TITLE
First draft of the perf example

### PR DESCRIPTION
**Pull request by aprokop**
Does not compile yet due to sethrj/swig#31.

### CODE REVIEW

**Comment by sethrj** [comment]
@aprokop , I fixed the bug (it was just a missing `out=` typemap in the copy-paste job) and added a test. Can you rebase your branch off the master fortran sample? You must have forked right before I rearranged the repo... :\

**Comment by aprokop** [comment]
@sethrj I don't think it is fully fixed yet. It works when one expects to return an address to a single variable. However, returning a pointer to an array does not properly work. The issue is that we need to provide an extra parameter (3rd one) to `c_f_pointer` that will indicate the array length. Otherwise, you are unable to use it as an array on the Fortran side from what I can see.

**Comment by aprokop** [comment]
Manually tweaking `formatrix.f90` to use
```Fortran                                                                                                                                     
  function swigf_Matrix_get_columns(self, row) &                                                                                                             
     result(fresult)                                                                                                                                         
   use, intrinsic :: ISO_C_BINDING                                                                                                                           
   integer(C_INT), pointer :: fresult(:)                                                                                                                     
   class(Matrix) :: self                                                                                                                                     
   integer(C_INT), intent(in) :: row                                                                                                                         
   call c_f_pointer(swigc_Matrix_get_columns(self%swigptr, row), fresult, [swigf_Matrix_row_nnz(self, row)])                                                 
  end function
  function swigf_Matrix_get_values(self, row) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   real(C_DOUBLE), pointer :: fresult(:)
   class(Matrix) :: self
   integer(C_INT), intent(in) :: row
   call c_f_pointer(swigc_Matrix_get_values(self%swigptr, row), fresult, [swigf_Matrix_row_nnz(self, row)])
  end function
```
works. Now just need some kind of automatic mechanism to do that.

**Comment by aprokop** [comment]
I updated the PR. It now carriers SWIG-generated files that were manually updated after generation to make things work. It implements three different loops, fine, medium, and coarse, for matrix-vector multiplication, and compares timings. It does not include 0-1 indices translation at the moment, we need to discuss this.

**Pull request merged**
